name: LobbySystem
main: eu.soulsmc.lobbysystem.LobbySystem
api-version: 1.21
folia-supported: true
version: ${project.version}
authors:
  - Lvcq_
  - Razuuu
commands:
  lobbysystem:
    aliases: [ ls ]
  build:
    aliases: [ b ]
  fish:
